repos:
  -   repo: 'https://github.com/psf/black'
      rev: '24.10.0'
      hooks:
      -   id: black
  -   repo: https://github.com/pycqa/isort
      rev: '5.13.2'
      hooks:
      -   id: isort
  -   repo: 'https://github.com/pycqa/flake8'
      rev: '7.1.1'  
      hooks:
      -   id: flake8
          additional_dependencies:
            -   flake8-bugbear
            -   flake8-print
  - repo: local
    hooks:
      -     id: pylint
            name: pylint
            entry: 'python -m pylint'
            language: system
            types: [python]



  -   repo: 'https://github.com/pre-commit/mirrors-mypy'
      rev: v1.11.2
      hooks:
      -   id: mypy
          additional_dependencies: [types-requests==2.31.0.9]
          exclude: 'test/.*\.py'     
  -   repo: 'https://github.com/jazzband/pip-tools'
      rev: '7.4.1'
      hooks:
      -   id: pip-compile
          name: pip-compile requirements/prod.in
          args: [requirements/prod.in]
          files: ^requirements/prod\.(in|txt)$     
      -   id: pip-compile
          name: pip-compile requirements/dev.in
          args: [requirements/dev.in]
          files: ^requirements/dev\.(in|txt)$    