# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 696)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 696))
        MainWindow.setMaximumSize(QtCore.QSize(2578, 1231))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet(
            "\n"
            "    QWidget#myWidget {\n"
            '        background-image: url("E:\\MAIN\\source\\repos\\Retsam\\tfc_halloween_launcher\\background.jpg");  /* Replace with the path to your image */\n'
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "        background-attachment: fixed; /* Optional, to prevent scrolling with the content */\n"
            "    }"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_nickname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nickname.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_nickname.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_nickname.setStyleSheet(
            "/* Modern Style QLineEdit */\n"
            ".QLineEdit {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "  color: #333;\n"
            "  padding: 10px;\n"
            "  font-size: 16px;\n"
            "  border-radius: 15px; /* Adjust the value to control the corner smoothness */\n"
            "}\n"
            "\n"
            ".QLineEdit:focus {\n"
            "  outline: none;\n"
            "  border-color: #4287f5;\n"
            "  background-color: #fff;\n"
            "}\n"
            "\n"
            ".QLineEdit::placeholder {\n"
            "  color: #999;\n"
            "}\n"
            "\n"
            ".QLineEdit:hover {\n"
            "  border-color: #999;\n"
            "}\n"
            ""
        )
        self.lineEdit_nickname.setObjectName("lineEdit_nickname")
        self.horizontalLayout_2.addWidget(self.lineEdit_nickname)
        self.pushButton_minecraft_dir = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_minecraft_dir.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_minecraft_dir.setMaximumSize(
            QtCore.QSize(200, 16777215)
        )
        self.pushButton_minecraft_dir.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 5px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_minecraft_dir.setObjectName("pushButton_minecraft_dir")
        self.horizontalLayout_2.addWidget(self.pushButton_minecraft_dir)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_install_shaders = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_install_shaders.setMinimumSize(QtCore.QSize(300, 80))
        self.pushButton_install_shaders.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 5px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_install_shaders.setObjectName(
            "pushButton_install_shaders"
        )
        self.horizontalLayout.addWidget(self.pushButton_install_shaders)
        self.pushButton_install_and_launch = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_install_and_launch.setMinimumSize(
            QtCore.QSize(300, 80)
        )
        self.pushButton_install_and_launch.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 5px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_install_and_launch.setObjectName(
            "pushButton_install_and_launch"
        )
        self.horizontalLayout.addWidget(self.pushButton_install_and_launch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_background = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_background.setText("")
        self.label_background.setPixmap(
            QtGui.QPixmap("../../../data/image/background.jpg")
        )
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.verticalLayout_2.addWidget(self.label_background)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_nickname.setPlaceholderText(
            _translate("MainWindow", "Ник игрока")
        )
        self.pushButton_minecraft_dir.setText(
            _translate("MainWindow", "Папка с игрой")
        )
        self.pushButton_install_shaders.setText(
            _translate("MainWindow", "Установить шейдеры")
        )
        self.pushButton_install_and_launch.setText(
            _translate("MainWindow", "Запустить TFC-Halloween")
        )
