# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1366, 696)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 696))
        MainWindow.setMaximumSize(QtCore.QSize(2578, 1184))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1366, 696))
        self.centralwidget.setStyleSheet(
            "\n"
            "    QWidget#myWidget {\n"
            '        background-image: url("E:\\MAIN\\source\\repos\\Retsam\\tfc_halloween_launcher\\background.jpg");  /* Replace with the path to your image */\n'
            "        background-repeat: no-repeat;\n"
            "        background-position: center;\n"
            "        background-attachment: fixed; /* Optional, to prevent scrolling with the content */\n"
            "    }"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_nickname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nickname.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_nickname.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_nickname.setStyleSheet(
            "/* Modern Style QLineEdit */\n"
            ".QLineEdit {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "  color: #333;\n"
            "  padding: 10px;\n"
            "  font-size: 16px;\n"
            "  border-radius: 15px; /* Adjust the value to control the corner smoothness */\n"
            "}\n"
            "\n"
            ".QLineEdit:focus {\n"
            "  outline: none;\n"
            "  border-color: #4287f5;\n"
            "  background-color: #fff;\n"
            "}\n"
            "\n"
            ".QLineEdit::placeholder {\n"
            "  color: #999;\n"
            "}\n"
            "\n"
            ".QLineEdit:hover {\n"
            "  border-color: #999;\n"
            "}\n"
            ""
        )
        self.lineEdit_nickname.setObjectName("lineEdit_nickname")
        self.verticalLayout_3.addWidget(self.lineEdit_nickname)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_password.setStyleSheet(
            "/* Modern Style QLineEdit */\n"
            ".QLineEdit {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "  color: #333;\n"
            "  padding: 10px;\n"
            "  font-size: 16px;\n"
            "  border-radius: 15px; /* Adjust the value to control the corner smoothness */\n"
            "}\n"
            "\n"
            ".QLineEdit:focus {\n"
            "  outline: none;\n"
            "  border-color: #4287f5;\n"
            "  background-color: #fff;\n"
            "}\n"
            "\n"
            ".QLineEdit::placeholder {\n"
            "  color: #999;\n"
            "}\n"
            "\n"
            ".QLineEdit:hover {\n"
            "  border-color: #999;\n"
            "}\n"
            ""
        )
        self.lineEdit_password.setEchoMode(
            QtWidgets.QLineEdit.EchoMode.Password
        )
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_3.addWidget(self.lineEdit_password)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_server_type = QtWidgets.QComboBox(
            parent=self.centralwidget
        )
        self.comboBox_server_type.setMinimumSize(QtCore.QSize(0, 60))
        self.comboBox_server_type.setMaximumSize(QtCore.QSize(16777215, 60))
        self.comboBox_server_type.setStyleSheet(
            "/* Modern Style QLineEdit */\n"
            ".QComboBox {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "  color: #333;\n"
            "  padding: 10px;\n"
            "  font-size: 16px;\n"
            "  border-radius: 15px; /* Adjust the value to control the corner smoothness */\n"
            "\n"
            "}\n"
            "\n"
            ".QComboBox:focus {\n"
            "  outline: none;\n"
            "  border-color: #4287f5;\n"
            "  background-color: #fff;\n"
            "}\n"
            "\n"
            ".QComboBox::placeholder {\n"
            "  color: #999;\n"
            "}\n"
            "\n"
            ".QComboBox:hover {\n"
            "  border-color: #999;\n"
            "}\n"
            "\n"
            "QComboBox:editable {\n"
            "    background: white;\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "QComboBox:on { /* shift the text when the popup opens */\n"
            "    padding-top: 3px;\n"
            "    padding-left: 4px;\n"
            "}\n"
            "\n"
            "\n"
            "QComboBox:on { /* shift the text when the popup opens */\n"
            "    padding-top: 3px;\n"
            "    padding-left: 4px;\n"
            "}\n"
            "\n"
            "QComboBox:drop-down {\n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right;\n"
            "    width: 15px;\n"
            "\n"
            "    border-left-width: 1px;\n"
            "    border-left-color: darkgray;\n"
            "    border-left-style: solid; /* just a single line */\n"
            "    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
            "    border-bottom-right-radius: 3px;\n"
            " border-radius: 15px; /* Adjust the value to control the corner smoothness */\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.comboBox_server_type.setObjectName("comboBox_server_type")
        self.comboBox_server_type.addItem("")
        self.comboBox_server_type.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_server_type)
        self.pushButton_minecraft_dir_disable_long_tern_save = (
            QtWidgets.QPushButton(parent=self.centralwidget)
        )
        self.pushButton_minecraft_dir_disable_long_tern_save.setMinimumSize(
            QtCore.QSize(200, 0)
        )
        self.pushButton_minecraft_dir_disable_long_tern_save.setMaximumSize(
            QtCore.QSize(200, 16777215)
        )
        self.pushButton_minecraft_dir_disable_long_tern_save.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 5px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_minecraft_dir_disable_long_tern_save.setObjectName(
            "pushButton_minecraft_dir_disable_long_tern_save"
        )
        self.verticalLayout_4.addWidget(
            self.pushButton_minecraft_dir_disable_long_tern_save
        )
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_install_and_launch = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_install_and_launch.setMinimumSize(
            QtCore.QSize(300, 80)
        )
        self.pushButton_install_and_launch.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 30px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_install_and_launch.setObjectName(
            "pushButton_install_and_launch"
        )
        self.verticalLayout_5.addWidget(self.pushButton_install_and_launch)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_information_text = QtWidgets.QLabel(
            parent=self.centralwidget
        )
        self.label_information_text.setMaximumSize(QtCore.QSize(300, 50))
        self.label_information_text.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.label_information_text.setStyleSheet(
            "            background-color: #3498db;\n"
            "            color: #ecf0f1;\n"
            "            padding: 15px;\n"
            "            font-size: 18px;\n"
            "            border-radius: 20px;"
        )
        self.label_information_text.setText("")
        self.label_information_text.setScaledContents(True)
        self.label_information_text.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter
        )
        self.label_information_text.setObjectName("label_information_text")
        self.verticalLayout_5.addWidget(self.label_information_text)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_choose_cape = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_choose_cape.setMinimumSize(QtCore.QSize(200, 70))
        self.pushButton_choose_cape.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 30px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_choose_cape.setObjectName("pushButton_choose_cape")
        self.gridLayout.addWidget(self.pushButton_choose_cape, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setStyleSheet(
            "/* Custom Style QGroupBox */\n"
            "QGroupBox {\n"
            "  font-size: 16px;\n"
            "  border: 2px solid #4287f5; /* Border color for the group box */\n"
            "  border-radius: 8px; /* Border radius for rounded corners */\n"
            "  margin-top: 10px; /* Adjust margin as needed */\n"
            "}\n"
            "\n"
            "QGroupBox::title {\n"
            "  subcontrol-origin: margin;\n"
            "  subcontrol-position: top center;\n"
            "  padding: 0 5px; /* Padding for the title text */\n"
            "}\n"
            "\n"
            "/* Apply the style for the child QRadioButton inside the QGroupBox */\n"
            "QGroupBox QRadioButton::indicator {\n"
            "  width: 20px;\n"
            "  height: 20px;\n"
            "  border-radius: 10px; /* Make the indicator circular */\n"
            "}\n"
            "\n"
            "QGroupBox QRadioButton::indicator:unchecked {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "}\n"
            "\n"
            "QGroupBox QRadioButton::indicator:checked {\n"
            "  border: 2px solid #4287f5;\n"
            "  background-color: #4287f5;\n"
            "}\n"
            "\n"
            "QGroupBox QRadioButton::indicator:hover {\n"
            "  border: 2px solid #999;\n"
            "}\n"
            "\n"
            "QGroupBox QRadioButton::indicator:checked:hover {\n"
            "  background-color: #3264ad;\n"
            "}\n"
            ""
        )
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_male = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_male.setStyleSheet(
            "/* Custom Style QCheckBox and QRadioButton */\n"
            "QCheckBox, QRadioButton {\n"
            "  spacing: 5px;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator, QRadioButton::indicator {\n"
            "  width: 20px;\n"
            "  height: 20px;\n"
            "  border-radius: 10px; /* Set border-radius to half of width/height for a circular shape */\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:unchecked, QRadioButton::indicator:unchecked {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
            "  border: 2px solid #4287f5;\n"
            "  background-color: #4287f5;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:hover, QRadioButton::indicator:hover {\n"
            "  border: 2px solid #999;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked:hover, QRadioButton::indicator:checked:hover {\n"
            "  background-color: #3264ad;\n"
            "}\n"
            ""
        )
        self.radioButton_male.setChecked(True)
        self.radioButton_male.setObjectName("radioButton_male")
        self.verticalLayout_6.addWidget(self.radioButton_male)
        self.radioButton_female = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_female.setStyleSheet(
            "/* Custom Style QCheckBox and QRadioButton */\n"
            "QCheckBox, QRadioButton {\n"
            "  spacing: 5px;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator, QRadioButton::indicator {\n"
            "  width: 20px;\n"
            "  height: 20px;\n"
            "  border-radius: 10px; /* Set border-radius to half of width/height for a circular shape */\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:unchecked, QRadioButton::indicator:unchecked {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
            "  border: 2px solid #4287f5;\n"
            "  background-color: #4287f5;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:hover, QRadioButton::indicator:hover {\n"
            "  border: 2px solid #999;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked:hover, QRadioButton::indicator:checked:hover {\n"
            "  background-color: #3264ad;\n"
            "}\n"
            ""
        )
        self.radioButton_female.setObjectName("radioButton_female")
        self.verticalLayout_6.addWidget(self.radioButton_female)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.pushButton_choose_skin = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_choose_skin.setMinimumSize(QtCore.QSize(200, 70))
        self.pushButton_choose_skin.setMaximumSize(QtCore.QSize(16777215, 70))
        self.pushButton_choose_skin.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #3A92F7;\n"
            "  border: none;\n"
            "  border-radius: 30px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #303EF7;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #1000F7;\n"
            "  border: 1px solid #00274D;\n"
            "}\n"
            ""
        )
        self.pushButton_choose_skin.setObjectName("pushButton_choose_skin")
        self.gridLayout.addWidget(self.pushButton_choose_skin, 0, 1, 1, 1)
        self.checkBox_is_install_shaders = QtWidgets.QCheckBox(
            parent=self.centralwidget
        )
        self.checkBox_is_install_shaders.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_is_install_shaders.setMaximumSize(
            QtCore.QSize(250, 16777215)
        )
        self.checkBox_is_install_shaders.setStyleSheet(
            "/* Custom Style QCheckBox */\n"
            "QCheckBox {\n"
            "  spacing: 5px;\n"
            "  font-size: 16px;\n"
            "\n"
            "}\n"
            "\n"
            "QCheckBox::indicator {\n"
            "  width: 20px;\n"
            "  height: 20px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:unchecked {\n"
            "  border: 2px solid #ccc;\n"
            "  background-color: #f9f9f9;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked {\n"
            "  border: 2px solid #4287f5;\n"
            "  background-color: #4287f5;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:hover {\n"
            "  border: 2px solid #999;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator:checked:hover {\n"
            "  background-color: #3264ad;\n"
            "}"
        )
        self.checkBox_is_install_shaders.setObjectName(
            "checkBox_is_install_shaders"
        )
        self.gridLayout.addWidget(self.checkBox_is_install_shaders, 3, 0, 1, 1)
        self.pushButton_delete_skin = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_delete_skin.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #FF0000; /* Red color */\n"
            "  border: none;\n"
            "  border-radius: 30px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #CC0000; /* Darker red on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #990000; /* Even darker red when pressed */\n"
            "  border: 1px solid #660000; /* Dark border when pressed */\n"
            "}\n"
            ""
        )
        self.pushButton_delete_skin.setObjectName("pushButton_delete_skin")
        self.gridLayout.addWidget(self.pushButton_delete_skin, 0, 2, 1, 1)
        self.pushButton_delete_cape = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.pushButton_delete_cape.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #FF0000; /* Red color */\n"
            "  border: none;\n"
            "  border-radius: 30px;\n"
            "  padding: 12px 24px;\n"
            "  color: #FFFFFF;\n"
            "  font-weight: bold;\n"
            "  text-align: center;\n"
            "  text-decoration: none;\n"
            "  font-size: 16px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #CC0000; /* Darker red on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "  background-color: #990000; /* Even darker red when pressed */\n"
            "  border: 1px solid #660000; /* Dark border when pressed */\n"
            "}\n"
            ""
        )
        self.pushButton_delete_cape.setObjectName("pushButton_delete_cape")
        self.gridLayout.addWidget(self.pushButton_delete_cape, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.label_background = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_background.setText("")
        self.label_background.setPixmap(
            QtGui.QPixmap("../../../data/image/background.jpg")
        )
        self.label_background.setScaledContents(True)
        self.label_background.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_background.setObjectName("label_background")
        self.verticalLayout_2.addWidget(self.label_background)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_nickname.setPlaceholderText(
            _translate("MainWindow", "Ник игрока")
        )
        self.lineEdit_password.setPlaceholderText(
            _translate("MainWindow", "Пароль")
        )
        self.comboBox_server_type.setItemText(
            0, _translate("MainWindow", "TFC Halloween")
        )
        self.comboBox_server_type.setItemText(
            1, _translate("MainWindow", "TFC Halloween TEST")
        )
        self.pushButton_minecraft_dir_disable_long_tern_save.setText(
            _translate("MainWindow", "Папка с игрой")
        )
        self.pushButton_install_and_launch.setText(
            _translate("MainWindow", "Запустить TFC-Halloween")
        )
        self.pushButton_choose_cape.setText(
            _translate("MainWindow", "Выбрать плащ")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Тип скина"))
        self.radioButton_male.setText(_translate("MainWindow", "Мужской"))
        self.radioButton_female.setText(_translate("MainWindow", "Женский"))
        self.pushButton_choose_skin.setText(
            _translate("MainWindow", "Выбрать скин")
        )
        self.checkBox_is_install_shaders.setText(
            _translate("MainWindow", "Установить шейдеры")
        )
        self.pushButton_delete_skin.setText(
            _translate("MainWindow", "Удалить скин")
        )
        self.pushButton_delete_cape.setText(
            _translate("MainWindow", "Удалить плащ")
        )
